# Generated by Django 4.1.3 on 2022-11-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='company',
            field=models.ManyToManyField(to='core.company'),
        ),
    ]
