# Generated by Django 4.1.3 on 2022-11-14 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tweet_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='company',
            new_name='companies',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='company',
            new_name='companies',
        ),
    ]
