# Generated by Django 3.2.16 on 2022-12-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=31)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('stock_price', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=63, null=True)),
                ('twitter_query_set', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
