# Generated by Django 4.1.3 on 2022-11-29 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('volume', models.PositiveIntegerField()),
                ('open', models.PositiveIntegerField()),
                ('close', models.PositiveIntegerField()),
                ('high', models.PositiveIntegerField()),
                ('low', models.PositiveIntegerField()),
                ('comapany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stock.company')),
            ],
        ),
    ]
