# Generated by Django 4.1.3 on 2022-12-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='market_cap',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
