# Generated by Django 4.1.3 on 2022-11-23 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='comapany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stock.company'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
