# Generated by Django 3.2.16 on 2022-12-10 15:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('companies', models.ManyToManyField(related_name='hashtags', to='stock.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('joined_date', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=511, null=True)),
                ('verified', models.BooleanField(blank=True, null=True)),
                ('followers_count', models.PositiveIntegerField(blank=True, null=True)),
                ('following_count', models.PositiveIntegerField(blank=True, null=True)),
                ('tweet_count', models.PositiveIntegerField(blank=True, null=True)),
                ('listed_count', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('post_date', models.DateTimeField()),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField()),
                ('cleaned_text', models.TextField(blank=True, null=True)),
                ('comment_number', models.PositiveIntegerField(blank=True, null=True)),
                ('retweet_number', models.PositiveIntegerField(blank=True, null=True)),
                ('like_number', models.PositiveIntegerField(blank=True, null=True)),
                ('sentiment_positive', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('sentiment_neutral', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('sentiment_negative', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('sentiment_uncertain', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('sentiment_compound', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)])),
                ('companies', models.ManyToManyField(related_name='tweets', to='stock.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tweets', to='tweet.twitteruser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('mode', models.CharField(choices=[('private', 'PRIVATE'), ('public', 'PUBLIC')], default='private', max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sets', to=settings.AUTH_USER_MODEL)),
                ('hashtags', models.ManyToManyField(related_name='sets', to='tweet.HashTag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hashtag',
            name='tweets',
            field=models.ManyToManyField(related_name='hashtags', to='tweet.Tweet'),
        ),
    ]
