# Generated by Django 4.1.3 on 2022-11-29 20:02

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import timescale.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('companies', models.ManyToManyField(related_name='hashtags', to='stock.company')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('text', models.TextField()),
                ('cleaned_text', models.TextField(blank=True, null=True)),
                ('comment_number', models.PositiveIntegerField(default=0)),
                ('retweet_number', models.PositiveIntegerField(default=0)),
                ('like_number', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('sentiment_pos', models.IntegerField()),
                ('sentiment_neu', models.IntegerField()),
                ('sentiment_neg', models.IntegerField()),
                ('sentiment_compound', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tweets', to='stock.company')),
                ('hashtag0', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tweets0', to='tweet.hashtag')),
                ('hashtag1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tweets1', to='tweet.hashtag')),
                ('hashtag2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tweets2', to='tweet.hashtag')),
                ('hashtag3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tweets3', to='tweet.hashtag')),
                ('hashtag4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tweets4', to='tweet.hashtag')),
                ('hashtag5', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tweets5', to='tweet.hashtag')),
                ('hashtag6', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tweets6', to='tweet.hashtag')),
                ('hashtag7', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tweets7', to='tweet.hashtag')),
                ('hashtag8', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tweets8', to='tweet.hashtag')),
                ('hashtag9', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tweets9', to='tweet.hashtag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tweets', to='tweet.twitteruser')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('timescale', django.db.models.manager.Manager()),
            ],
        ),
    ]
