# Generated by Django 4.1.3 on 2022-11-17 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('post_date', models.DateTimeField()),
                ('text', models.TextField()),
                ('comment_number', models.PositiveIntegerField()),
                ('retweet_number', models.PositiveIntegerField()),
                ('like_number', models.PositiveIntegerField()),
                ('companies', models.ManyToManyField(related_name='tweets', to='stock.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tweet.twitteruser')),
            ],
        ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('companies', models.ManyToManyField(related_name='hashtags', to='stock.company')),
                ('tweets', models.ManyToManyField(related_name='hashtags', to='tweet.tweet')),
            ],
        ),
    ]
