# Generated by Django 4.1.3 on 2022-11-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
