# Generated by Django 4.1.3 on 2022-11-29 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tweet',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='tweet',
            name='hashtag0',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tweets0', to='tweet.hashtag'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='hashtag1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tweets1', to='tweet.hashtag'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='hashtag2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tweets2', to='tweet.hashtag'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='hashtag3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tweets3', to='tweet.hashtag'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='hashtag4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tweets4', to='tweet.hashtag'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='hashtag5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tweets5', to='tweet.hashtag'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='hashtag6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tweets6', to='tweet.hashtag'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='hashtag7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tweets7', to='tweet.hashtag'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='hashtag8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tweets8', to='tweet.hashtag'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='hashtag9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tweets9', to='tweet.hashtag'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='sentiment_compound',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='sentiment_neg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='sentiment_neu',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='sentiment_pos',
            field=models.IntegerField(default=0),
        ),
    ]
