# Generated by Django 4.1.3 on 2022-11-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_alter_twitteruser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='cleaned_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
