# Generated by Django 4.1.3 on 2022-11-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_alter_hashtag_companies_alter_tweet_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
