# Generated by Django 4.1.3 on 2022-11-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0006_tweet_sourde_twitteruser_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='sourde',
            new_name='source',
        ),
    ]
