# Generated by Django 4.1.3 on 2022-12-06 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweet', '0007_rename_sourde_tweet_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='comment_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='like_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='retweet_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tweets', to='tweet.twitteruser'),
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('mode', models.CharField(choices=[('private', 'PRIVATE'), ('public', 'PUBLIC')], default='private', max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(related_name='following_sets', to=settings.AUTH_USER_MODEL)),
                ('hashtags', models.ManyToManyField(related_name='sets', to='tweet.hashtag')),
            ],
        ),
    ]
