# Generated by Django 3.2.16 on 2022-12-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('authentication', '0002_alter_favorite_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'favorite_ct', 'favorite_id')},
        ),
    ]
