name: "Build And Publish Public Docker Container to GitHub Packages"

# This Action runs every time a branch is merged to main
# Note: There is no "on merge event", so we use "push" event since every "merge" is also a "push"
# Tip: To assure that work is secure the main should be protected agains direct pushes and only accept pull requests
on:
  push:
    branches: [ "main"]

  #Allows you to run it manually from Actions tab in GitHub repo
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Create env file
        run: |
          echo "${{ secrets.SENTITWEET_ENV_FILE_DEAFULT }}" > .env

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      #It will tag the container with 
      # 1. branch name (ghcr.io/sentistock/sentitweet:main)
      # 2. version tag according to Semver guidelines
      # 3. "latest" (ghcr.io/sentistock/sentitweet:latest)
      # 4. unique sha
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          flavor: |
            latest=true

      - name: Build and push Docker container image to GitHub Repository
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true